name: Deployment with Docker

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: |
          VERSION=${{ github.sha }}
          docker build -t sparshsethi15/cross-that-zero:$VERSION .

      - name: Push image to Dockerhub
        run: |
          VERSION=${{ github.sha }}
          docker push sparshsethi15/cross-that-zero:$VERSION

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ${{ secrets.KUBE_CONFIG }}
        run: |
          IMAGE_NAME=sparshsethi15/cross-that-zero
          VERSION=${{ github.sha }}
          echo "$KUBECONFIG" | base64 --decode > kubeconfig.yaml
          chmod 600 kubeconfig.yaml
          kubectl --kubeconfig="kubeconfig.yaml" set image deployment/blogpoint blogpoint=$IMAGE_NAME:$VERSION
          kubectl --kubeconfig="kubeconfig.yaml" rollout status deployment/cross-that-zero
