
name: Java CI with Maven

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven


      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Deploy to EC2

        run: |
          echo "PROFILE=${{ env.PROFILE }}"
          echo "${{ secrets.EC2_SSH_KEY }}" > CrossThatZero.pem && chmod 600 CrossThatZero.pem
          scp -o StrictHostKeyChecking=no -i CrossThatZero.pem target/CrossThatZero-backend-0.0.1-SNAPSHOT.jar ubuntu@3.129.125.64:/home/ubuntu/cross-that-zero_backend/target
          ssh -o StrictHostKeyChecking=no -i CrossThatZero.pem ubuntu@3.129.125.64 "sudo lsof -t -i:8080 | xargs -r sudo kill -9 && nohup java -jar /home/ubuntu/cross-that-zero_backend/target/CrossThatZero-backend-0.0.1-SNAPSHOT.jar --DB_USERNAME=${{ secrets.DB_USERNAME }} --DB_PASSWORD=${{ secrets.DB_PASSWORD }} --PROFILE=prod &"
